import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { createInterface } from 'node:readline/promises';
import { Writable } from 'node:stream';
import type { CatalogSearchResult } from '../../agent/catalog/providers/index.ts';
import type { AgentCatalogStore } from '../../agent/catalog/store.ts';
import type { SourceLock } from '../../agent/catalog/types/index.ts';
import type { MCPConfig } from '../../agent/tools/types.ts';

const CREDENTIAL_NAME = /(token|key|secret|password|auth|bearer)/i;
const ENV_PLACEHOLDER = /(\$\{env:([A-Za-z_][A-Za-z0-9_]*)\}|\{([A-Za-z_][A-Za-z0-9_]*)\})/g;
const LEGACY_AUTOGENERATED_ENV_DEFAULTS: Record<string, string> = {
  SKILLS_REGISTRY_URL: 'https://skills.sh',
  MCP_REGISTRY_URL: 'https://registry.modelcontextprotocol.io',
  GITHUB_TOKEN: '',
  NODE_ENV: 'development',
  LLM_MODEL: 'llama3.1',
  OLLAMA_BASE_URL: 'http://localhost:11434',
  OPENROUTER_API_KEY: '',
  OPEN_ROUTER_KEY: '',
  OPENROUTER_KEY: '',
  OPENAI_API_KEY: '',
  ANTHROPIC_API_KEY: '',
};

interface CredentialRequirement {
  envName: string;
  name: string;
  description?: string;
  sourceUrl?: string;
}

class SecretPromptOutput extends Writable {
  readonly isTTY = true;
  readonly columns = process.stdout.columns ?? 80;
  private muted = false;

  setMuted(muted: boolean): void {
    this.muted = muted;
  }

  override _write(
    chunk: Buffer | string,
    encoding: BufferEncoding,
    callback: (error?: Error | null) => void,
  ): void {
    if (this.muted) {
      callback();
      return;
    }
    process.stdout.write(chunk, encoding, callback);
  }
}

async function questionSecret(
  input: ReturnType<typeof createInterface>,
  output: SecretPromptOutput,
  prompt: string,
): Promise<string> {
  process.stdout.write(prompt);
  output.setMuted(true);
  try {
    return await input.question('');
  } finally {
    output.setMuted(false);
    process.stdout.write('\n');
  }
}

function mergeUnique(requirements: CredentialRequirement[]): CredentialRequirement[] {
  return requirements.filter((item, index, array) =>
    array.findIndex((candidate) => candidate.envName === item.envName) === index,
  );
}

function parseEnvNames(value: string): string[] {
  const names = new Set<string>();
  for (const match of value.matchAll(ENV_PLACEHOLDER)) {
    const envName = match[2] ?? match[3];
    if (envName) {
      names.add(envName.trim());
    }
  }
  return Array.from(names);
}

export function collectReferencedEnvNames(config: MCPConfig | undefined): string[] {
  if (!config) {
    return [];
  }

  const names = new Set<string>();
  const candidates: Array<Record<string, string> | undefined> = [
    'env' in config ? config.env : undefined,
    'headers' in config ? config.headers : undefined,
  ];

  for (const group of candidates) {
    if (!group) {
      continue;
    }
    for (const value of Object.values(group)) {
      for (const envName of parseEnvNames(String(value ?? ''))) {
        names.add(envName);
      }
    }
  }

  return Array.from(names);
}

function extractCredentialRequirements(result: CatalogSearchResult): CredentialRequirement[] {
  if (result.kind !== 'mcp' || result.install.type !== 'mcp') {
    return [];
  }

  const fromRegistry = (result.credentials ?? []).map((credential) => ({
    envName: credential.envName ?? credential.name,
    name: credential.name,
    description: credential.description,
    sourceUrl: credential.sourceUrl,
  }));

  const inferred = new Set<string>();
  const envMap = 'env' in result.install.vscode ? result.install.vscode.env : undefined;
  if (envMap) {
    for (const value of Object.values(envMap)) {
      for (const envName of parseEnvNames(value)) {
        if (CREDENTIAL_NAME.test(envName)) {
          inferred.add(envName);
        }
      }
    }
  }

  const headerMap = 'headers' in result.install.vscode ? result.install.vscode.headers : undefined;
  if (headerMap) {
    for (const value of Object.values(headerMap)) {
      for (const envName of parseEnvNames(value)) {
        if (CREDENTIAL_NAME.test(envName)) {
          inferred.add(envName);
        }
      }
    }
  }

  const inferredRequirements = Array.from(inferred).map((name) => ({ envName: name, name }));
  return mergeUnique([...fromRegistry, ...inferredRequirements]);
}

function parseEnvFile(content: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }
    const separator = line.indexOf('=');
    if (separator <= 0) {
      continue;
    }
    const key = line.slice(0, separator).trim();
    const value = line.slice(separator + 1).trim();
    map.set(key, value);
  }
  return map;
}

function formatEnvValue(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function normalizeStoredEnvValue(value: string): string {
  return value.trim().replace(/^['"]|['"]$/g, '');
}

function syncEnvFile(
  filePath: string,
  values: Record<string, string>,
  requiredNames: Iterable<string> = Object.keys(values),
): void {
  const existing = existsSync(filePath) ? readFileSync(filePath, 'utf8') : '';
  const required = new Set(requiredNames);
  const lines = (existing ? existing.split(/\r?\n/) : []).filter((line) => {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$/);
    if (!match?.[1]) {
      return true;
    }
    const key = match[1];
    const legacyDefault = LEGACY_AUTOGENERATED_ENV_DEFAULTS[key];
    if (typeof legacyDefault === 'undefined' || required.has(key)) {
      return true;
    }
    return normalizeStoredEnvValue(match[2] ?? '') !== legacyDefault;
  });
  const indexes = new Map<string, number>();

  lines.forEach((line, index) => {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/);
    if (match?.[1]) {
      indexes.set(match[1], index);
    }
  });

  for (const [key, value] of Object.entries(values)) {
    const rendered = `${key}=${formatEnvValue(value)}`;
    const existingIndex = indexes.get(key);
    if (typeof existingIndex === 'number') {
      lines[existingIndex] = rendered;
    } else {
      lines.push(rendered);
    }
  }

  const normalized = lines.join('\n').replace(/\n*$/, '\n');
  writeFileSync(filePath, normalized, 'utf8');
}

function ensureEnvFileEntries(rootDir: string, names: Iterable<string>): void {
  const uniqueNames = Array.from(new Set(Array.from(names).filter(Boolean)));
  const envFile = path.resolve(rootDir, '.env.maia');
  const existing = existsSync(envFile) ? parseEnvFile(readFileSync(envFile, 'utf8')) : new Map<string, string>();
  const toPersist: Record<string, string> = {};

  for (const name of uniqueNames) {
    if (Object.prototype.hasOwnProperty.call(process.env, name) || existing.has(name)) {
      continue;
    }
    toPersist[name] = '';
  }

  syncEnvFile(envFile, toPersist, uniqueNames);
}

export function ensureMcpEnvFileEntries(store: AgentCatalogStore, config: MCPConfig | undefined): void {
  const rootDir = path.dirname(store.getPaths().manifest);
  ensureEnvFileEntries(rootDir, collectReferencedEnvNames(config));
}

export function ensureLockMcpEnvFileEntries(
  store: Pick<AgentCatalogStore, 'getPaths'>,
  lock: SourceLock,
): void {
  const rootDir = path.dirname(store.getPaths().manifest);
  const names = Object.values(lock.packages)
    .filter((pkg) => pkg.type === 'mcp')
    .flatMap((pkg) => collectReferencedEnvNames(pkg.vscode));
  ensureEnvFileEntries(rootDir, names);
}

export async function configureMcpCredentialsFromResult(
  store: AgentCatalogStore,
  result: CatalogSearchResult,
): Promise<void> {
  const requirements = extractCredentialRequirements(result);
  if (requirements.length === 0) {
    ensureMcpEnvFileEntries(store, 'install' in result && result.install.type === 'mcp' ? result.install.vscode : undefined);
    return;
  }

  const rootDir = path.dirname(store.getPaths().manifest);
  const envFile = path.resolve(rootDir, '.env.maia');
  const existing = existsSync(envFile) ? parseEnvFile(readFileSync(envFile, 'utf8')) : new Map<string, string>();
  const toPersist: Record<string, string> = {};

  console.log(`MCP "${result.name}" may require specific credentials. We will configure them in .env.maia: ${envFile}`);
  const interactive = Boolean(process.stdin.isTTY && process.stdout.isTTY);
  const secretOutput = interactive ? new SecretPromptOutput() : null;
  const input = interactive && secretOutput
    ? createInterface({ input: process.stdin, output: secretOutput, terminal: true })
    : null;

  try {
    for (const requirement of requirements) {
      const hasProcessValue = Boolean(process.env[requirement.envName]);
      const hasEnvFileValue = Boolean(existing.get(requirement.envName));
      if (hasProcessValue || hasEnvFileValue) {
        continue;
      }

      if (requirement.description) {
        console.log(`- ${requirement.envName}: ${requirement.description}`);
      } else {
        console.log(`- ${requirement.envName}`);
      }
      if (requirement.sourceUrl) {
        console.log(`  URL: ${requirement.sourceUrl}`);
      }

      if (!input || !secretOutput) {
        console.log(`  Set ${requirement.envName} manually in .env.maia to enable this MCP.`);
        toPersist[requirement.envName] = '';
        continue;
      }

      const value = (await questionSecret(
        input,
        secretOutput,
        `  Paste the value for ${requirement.envName} (input hidden; Enter to skip): `,
      )).trim();
      toPersist[requirement.envName] = value;
    }
  } finally {
    input?.close();
  }

  if (Object.keys(toPersist).length > 0 || requirements.length > 0) {
    syncEnvFile(envFile, toPersist, requirements.map((requirement) => requirement.envName));
  }

  if (Object.keys(toPersist).length > 0) {
    console.log(`Credentials file updated at ${envFile}`);
  }
}
